include:
  - template: Jobs/Container-Scanning.gitlab-ci.yml

stages:
  - check
  - build
  - publish
  - scan

variables:
  STORAGE_DRIVER: vfs
  BUILDAH_FORMAT: docker
  DOCKERHUB_IMAGE: tdolfen/papra-mail-ingestion
  CS_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG-amd64

lint:
  stage: check
  image: oven/bun:1-alpine
  script:
    - bun install --frozen-lockfile
    - bun run lint

typecheck:
  stage: check
  image: oven/bun:1-alpine
  script:
    - bun install --frozen-lockfile
    - bun run typecheck

.builder: &builder
  image: quay.io/buildah/stable
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | buildah login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/

build-amd64:
  <<: *builder
  stage: build
  tags:
    - saas-linux-small-amd64
  script:
    - >
      buildah build
      --platform=linux/amd64
      -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG-amd64 .
    - buildah push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG-amd64

build-arm64:
  <<: *builder
  stage: build
  tags:
    - saas-linux-small-arm64
  script:
    - >
      buildah build
      --platform=linux/arm64/v8
      -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG-arm64 .
    - buildah push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG-arm64

publish:
  <<: *builder
  stage: publish
  needs: ["build-amd64", "build-arm64"]
  tags:
    - saas-linux-small-amd64
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | buildah login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - echo "$DOCKERHUB_PASS" | buildah login -u "$DOCKERHUB_USER" --password-stdin docker.io
  script:
    # GitLab registry
    - buildah manifest create $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - buildah manifest add $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG docker://$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG-amd64
    - buildah manifest add $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG docker://$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG-arm64
    - buildah manifest push --all $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - buildah manifest create $CI_REGISTRY_IMAGE:latest
    - buildah manifest add $CI_REGISTRY_IMAGE:latest docker://$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG-amd64
    - buildah manifest add $CI_REGISTRY_IMAGE:latest docker://$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG-arm64
    - buildah manifest push --all $CI_REGISTRY_IMAGE:latest
    # Docker Hub
    - buildah manifest create $DOCKERHUB_IMAGE:$CI_COMMIT_TAG
    - buildah manifest add $DOCKERHUB_IMAGE:$CI_COMMIT_TAG docker://$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG-amd64
    - buildah manifest add $DOCKERHUB_IMAGE:$CI_COMMIT_TAG docker://$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG-arm64
    - buildah manifest push --all $DOCKERHUB_IMAGE:$CI_COMMIT_TAG
    - buildah manifest create $DOCKERHUB_IMAGE:latest
    - buildah manifest add $DOCKERHUB_IMAGE:latest docker://$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG-amd64
    - buildah manifest add $DOCKERHUB_IMAGE:latest docker://$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG-arm64
    - buildah manifest push --all $DOCKERHUB_IMAGE:latest

container_scanning:
  stage: scan
  needs: ["publish"]
  variables:
    GIT_STRATEGY: fetch
    CS_DOCKERFILE_PATH: Dockerfile
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/
